services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-dcr-lifecycle-manager-test
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./target/keycloak-dcr-lifecycle-manager.jar:/opt/keycloak/providers/keycloak-dcr-lifecycle-manager.jar